### ISSUE TITLE
Dimension mismatch while trying to run ML45

### ISSUE THREAD

**Issue by Lan131** [suyoung-lee/SDVT#3]
Traceback (most recent call last):
  File "main.py", line 174, in <module>
    main()
  File "main.py", line 170, in main
    learner.train()
  File "/home/research/lanier.m/Desktop/SDVT-master/metalearner_ml45_SDVT.py", line 253, in train
    self.log(None, None, start_time)
  File "/home/research/lanier.m/Desktop/SDVT-master/metalearner_ml45_SDVT.py", line 558, in log
    save_episode_successes=save_episode_successes,
  File "/home/research/lanier.m/Desktop/SDVT-master/utils/evaluation.py", line 165, in evaluate_metaworld
    state[:,:39] = state2.clone() #varibad wrapper has one more 'done' dimension
RuntimeError: The expanded size of the tensor (13) must match the existing size (12) at non-singleton dimension 1.  Target sizes: [10, 13].  Tensor sizes: [10, 12]

**Comment by suyoung-lee** [comment]
Hi

Thank you for bringing this to my attention. Unfortunately, I'm not actively maintaining this repo. However, I've never experienced and cannot reproduce that error based on the information provided. To effectively address the issue, I would need more details on how you're running the code.

In the future, the most helpful way to report an issue is to include the **exact command line** you used to run the code, along with **details of your environment and the versions of the dependencies** (e.g., via pip list). Without this, it becomes quite difficult to troubleshoot, as errors like this often stem from mismatches in library versions or differences in environment setups.

From the error message, it seems likely that the issue is related to the version of the MetaWorld environment, which has been evolving. Keeping track of library versions helps ensure compatibility across different setups. (refer to the README about the MetaWorld version required)

I look forward to your updated details so I can resolve this as efficiently as possible. Thanks for your understanding!

Best regards,

**Comment by Lan131** [comment]
Thank you. The issue name indicated the issue. I was trying to run ML45 as you instruct in the read me:

 python main.py --env-type ml45-SDVT
 
 
 From the error in line 165 of evaluation:
 state[:,:39] = state2.clone() #varibad wrapper has one more 'done' dimension
 
It seems that there is some left over hard code from the varibad implementation that is independent of the metaworld installation. If I comment out that line the error goes away but then policy.py throws an error at line 198:
state = (state - self.state_rms.mean) / torch.sqrt(self.state_rms.var + 1e-8)


because self.state_rms.mean is size 13 and state is 10 by 12.
